name: PluginBoob
version: 1.1
main: com.example.PluginBoob
api-version: 1.21
description: Plugin to change player size
commands:
  size:
    description: Set the size of a player
    usage: /size <player> <height>
permissions:
  pluginboob.setheight.065:
    description: Allows setting height to 0.65
    default: op
  pluginboob.setheight.075:
    description: Allows setting height to 0.75
    default: op
  pluginboob.setheight.085:
    description: Allows setting height to 0.85
    default: op
